In [1]:
from netCDF4 import Dataset  # dataset allows us to read the netcdf4 files
import bisect
import os
import pandas as pd
import numpy as np
import time
%matplotlib inline
import xarray as xr #7878

In [2]:
da=xr.open_mfdataset(r"C:\Users\futil\OneDrive\GIZ\Run2\*01.nc")
da

C:\Users\futil\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: In xarray version 0.15 the default behaviour of `open_mfdataset`
will change. To retain the existing behavior, pass
combine='nested'. To use future default behavior, pass
combine='by_coords'. See
http://xarray.pydata.org/en/stable/combining.html#combining-multi

  """Entry point for launching an IPython kernel.
C:\Users\futil\Anaconda3\lib\site-packages\xarray\backends\api.py:931: FutureWarning: The datasets supplied have global dimension coordinates. You may want
to use the new `combine_by_coords` function (or the
`combine='by_coords'` option to `open_mfdataset`) to order the datasets
before concatenation. Alternatively, to continue concatenating based
on the order the datasets are supplied in future, please use the new
`combine_nested` function (or the `combine='nested'` option to
open_mfdataset).
  from_openmfds=True,

<xarray.Dataset>
Dimensions:   (ID: 77168, RoseDir: 16, Turb: 4, hgt: 4, normData: 2)
Coordinates:
  * RoseDir   (RoseDir) object 'N' 'NNE' 'NE' 'ENE' 'E' ... 'W' 'WNW' 'NW' 'NNW'
  * Turb      (Turb) object 'Turbine 1' 'Turbine 2' 'Turbine 3' 'Turbine 4'
  * hgt       (hgt) int32 50 80 100 150
  * normData  (normData) object 'loc' 'scale'
    lat       (ID) float64 dask.array<chunksize=(880,), meta=np.ndarray>
    lon       (ID) float32 dask.array<chunksize=(880,), meta=np.ndarray>
  * ID        (ID) int64 0 1 2 3 4 5 6 ... 77162 77163 77164 77165 77166 77167
Data variables:
    CF        (ID, hgt, Turb) float64 dask.array<chunksize=(880, 4, 4), meta=np.ndarray>
    Power     (ID, hgt, Turb) float64 dask.array<chunksize=(880, 4, 4), meta=np.ndarray>
    Rose      (ID, hgt, RoseDir) float64 dask.array<chunksize=(880, 4, 16), meta=np.ndarray>
    Norn      (ID, hgt, normData) float32 dask.array<chunksize=(880, 4, 2), meta=np.ndarray>

In [25]:
# da=xr.open_mfdataset(r"C:\AllRun\*10.nc",combine='by_coords')
# da

In [5]:
CFdictionary = {'lat': np.array(da['lat']), 'lon': np.array(da['lon']),'ID':np.array(da['ID'])}

In [6]:
HGT=["50","80","100","150"]
NameList2=[]

for i in HGT:
    NameDir=list(map(lambda x: x+"-"+i,np.array(da['Turb'])))
    NameList2.extend(NameDir)
    
print(len(NameList2))
print()
CFList=(list(map(lambda x:'Capacity Factor [%]-'+x,NameList2)))

CFData=[]
for i in np.array(da['hgt']):
    for j in np.array(da['Turb']):  
        CFData.append(np.array(da['CF'].sel(hgt=i,Turb=j)))


print(CFList)
print(len(CFList))
print(np.shape(CFData))
print()

WindPowerList=(list(map(lambda x:'Wind Power [MWh/year]-'+x,NameList2)))

PowerData=[]
for i in np.array(da['hgt']):
    for j in np.array(da['Turb']):  
        PowerData.append(np.array(da['Power'].sel(hgt=i,Turb=j)))

print(WindPowerList)
print(np.shape(PowerData))

16

['Capacity Factor [%]-Turbine 1-50', 'Capacity Factor [%]-Turbine 2-50', 'Capacity Factor [%]-Turbine 3-50', 'Capacity Factor [%]-Turbine 4-50', 'Capacity Factor [%]-Turbine 1-80', 'Capacity Factor [%]-Turbine 2-80', 'Capacity Factor [%]-Turbine 3-80', 'Capacity Factor [%]-Turbine 4-80', 'Capacity Factor [%]-Turbine 1-100', 'Capacity Factor [%]-Turbine 2-100', 'Capacity Factor [%]-Turbine 3-100', 'Capacity Factor [%]-Turbine 4-100', 'Capacity Factor [%]-Turbine 1-150', 'Capacity Factor [%]-Turbine 2-150', 'Capacity Factor [%]-Turbine 3-150', 'Capacity Factor [%]-Turbine 4-150']
16
(16, 77168)

['Wind Power [MWh/year]-Turbine 1-50', 'Wind Power [MWh/year]-Turbine 2-50', 'Wind Power [MWh/year]-Turbine 3-50', 'Wind Power [MWh/year]-Turbine 4-50', 'Wind Power [MWh/year]-Turbine 1-80', 'Wind Power [MWh/year]-Turbine 2-80', 'Wind Power [MWh/year]-Turbine 3-80', 'Wind Power [MWh/year]-Turbine 4-80', 'Wind Power [MWh/year]-Turbine 1-100', 'Wind Power [MWh/year]-Turbine 2-100', 'Wind Power [MWh/year]-Turbine 3-100', 'Wind Power [MWh/year]-Turbine 4-100', 'Wind Power [MWh/year]-Turbine 1-150', 'Wind Power [MWh/year]-Turbine 2-150', 'Wind Power [MWh/year]-Turbine 3-150', 'Wind Power [MWh/year]-Turbine 4-150']
(16, 77168)

In [7]:
NormList=[]

for i in HGT:
    NameDir=list(map(lambda x: x+"-"+i,np.array(da['normData'])))
    NormList.extend(NameDir)    
print(NormList)

NormData=[]
for i in np.array(da['hgt']):
    for j in np.array(da['normData']):  
        NormData.append(np.array(da['Norn'].sel(hgt=i,normData=j)))
print(np.shape(NormData))

['loc-50', 'scale-50', 'loc-80', 'scale-80', 'loc-100', 'scale-100', 'loc-150', 'scale-150']
(8, 77168)

In [8]:
CFdictionary.update(zip(CFList, CFData))

In [9]:
CFdictionary

{'lat': array([-20.58840942, -20.60075378, -20.61306763, ..., -34.88233185,
        -34.89027405, -34.8982048 ]),
 'lon': array([31.659058, 31.612762, 31.566467, ..., 20.04486 , 19.990234,
        19.935608], dtype=float32),
 'ID': array([    0,     1,     2, ..., 77165, 77166, 77167], dtype=int64),
 'Capacity Factor [%]-Turbine 1-50': array([15.831, 15.938, 15.754, ..., 59.981, 60.608, 61.061]),
 'Capacity Factor [%]-Turbine 2-50': array([15.32 , 15.423, 15.245, ..., 58.741, 59.379, 59.84 ]),
 'Capacity Factor [%]-Turbine 3-50': array([16.23 , 16.34 , 16.152, ..., 60.653, 61.235, 61.651]),
 'Capacity Factor [%]-Turbine 4-50': array([ 7.223,  7.284,  7.195, ..., 42.346, 43.115, 43.678]),
 'Capacity Factor [%]-Turbine 1-80': array([22.427, 22.653, 22.438, ..., 61.962, 62.46 , 62.869]),
 'Capacity Factor [%]-Turbine 2-80': array([21.691, 21.91 , 21.702, ..., 60.758, 61.268, 61.686]),
 'Capacity Factor [%]-Turbine 3-80': array([22.994, 23.225, 23.004, ..., 62.464, 62.902, 63.261]),
 'Capacity Factor [%]-Turbine 4-80': array([10.794, 10.936, 10.831, ..., 44.81 , 45.459, 45.983]),
 'Capacity Factor [%]-Turbine 1-100': array([26.022, 26.115, 25.981, ..., 62.856, 63.288, 63.66 ]),
 'Capacity Factor [%]-Turbine 2-100': array([25.17 , 25.261, 25.131, ..., 61.673, 62.116, 62.496]),
 'Capacity Factor [%]-Turbine 3-100': array([26.67 , 26.764, 26.626, ..., 63.247, 63.614, 63.931]),
 'Capacity Factor [%]-Turbine 4-100': array([12.948, 13.019, 12.958, ..., 45.976, 46.552, 47.034]),
 'Capacity Factor [%]-Turbine 1-150': array([32.481, 32.266, 32.055, ..., 64.65 , 64.965, 65.246]),
 'Capacity Factor [%]-Turbine 2-150': array([31.449, 31.241, 31.037, ..., 63.514, 63.837, 64.125]),
 'Capacity Factor [%]-Turbine 3-150': array([33.247, 33.027, 32.811, ..., 64.723, 64.969, 65.189]),
 'Capacity Factor [%]-Turbine 4-150': array([17.242, 17.122, 17.006, ..., 48.395, 48.824, 49.198])}

In [10]:
CFdictionary.update(zip(WindPowerList, PowerData))

In [11]:
CFdictionary

{'lat': array([-20.58840942, -20.60075378, -20.61306763, ..., -34.88233185,
        -34.89027405, -34.8982048 ]),
 'lon': array([31.659058, 31.612762, 31.566467, ..., 20.04486 , 19.990234,
        19.935608], dtype=float32),
 'ID': array([    0,     1,     2, ..., 77165, 77166, 77167], dtype=int64),
 'Capacity Factor [%]-Turbine 1-50': array([15.831, 15.938, 15.754, ..., 59.981, 60.608, 61.061]),
 'Capacity Factor [%]-Turbine 2-50': array([15.32 , 15.423, 15.245, ..., 58.741, 59.379, 59.84 ]),
 'Capacity Factor [%]-Turbine 3-50': array([16.23 , 16.34 , 16.152, ..., 60.653, 61.235, 61.651]),
 'Capacity Factor [%]-Turbine 4-50': array([ 7.223,  7.284,  7.195, ..., 42.346, 43.115, 43.678]),
 'Capacity Factor [%]-Turbine 1-80': array([22.427, 22.653, 22.438, ..., 61.962, 62.46 , 62.869]),
 'Capacity Factor [%]-Turbine 2-80': array([21.691, 21.91 , 21.702, ..., 60.758, 61.268, 61.686]),
 'Capacity Factor [%]-Turbine 3-80': array([22.994, 23.225, 23.004, ..., 62.464, 62.902, 63.261]),
 'Capacity Factor [%]-Turbine 4-80': array([10.794, 10.936, 10.831, ..., 44.81 , 45.459, 45.983]),
 'Capacity Factor [%]-Turbine 1-100': array([26.022, 26.115, 25.981, ..., 62.856, 63.288, 63.66 ]),
 'Capacity Factor [%]-Turbine 2-100': array([25.17 , 25.261, 25.131, ..., 61.673, 62.116, 62.496]),
 'Capacity Factor [%]-Turbine 3-100': array([26.67 , 26.764, 26.626, ..., 63.247, 63.614, 63.931]),
 'Capacity Factor [%]-Turbine 4-100': array([12.948, 13.019, 12.958, ..., 45.976, 46.552, 47.034]),
 'Capacity Factor [%]-Turbine 1-150': array([32.481, 32.266, 32.055, ..., 64.65 , 64.965, 65.246]),
 'Capacity Factor [%]-Turbine 2-150': array([31.449, 31.241, 31.037, ..., 63.514, 63.837, 64.125]),
 'Capacity Factor [%]-Turbine 3-150': array([33.247, 33.027, 32.811, ..., 64.723, 64.969, 65.189]),
 'Capacity Factor [%]-Turbine 4-150': array([17.242, 17.122, 17.006, ..., 48.395, 48.824, 49.198]),
 'Wind Power [MWh/year]-Turbine 1-50': array([ 3.744,  3.77 ,  3.726, ..., 14.187, 14.335, 14.442]),
 'Wind Power [MWh/year]-Turbine 2-50': array([ 3.731,  3.756,  3.713, ..., 14.305, 14.46 , 14.573]),
 'Wind Power [MWh/year]-Turbine 3-50': array([ 4.265,  4.294,  4.245, ..., 15.94 , 16.092, 16.202]),
 'Wind Power [MWh/year]-Turbine 4-50': array([ 1.898,  1.914,  1.891, ..., 11.128, 11.331, 11.479]),
 'Wind Power [MWh/year]-Turbine 1-80': array([ 5.304,  5.358,  5.307, ..., 14.655, 14.773, 14.87 ]),
 'Wind Power [MWh/year]-Turbine 2-80': array([ 5.282,  5.336,  5.285, ..., 14.796, 14.92 , 15.022]),
 'Wind Power [MWh/year]-Turbine 3-80': array([ 6.043,  6.104,  6.045, ..., 16.416, 16.531, 16.625]),
 'Wind Power [MWh/year]-Turbine 4-80': array([ 2.837,  2.874,  2.846, ..., 11.776, 11.947, 12.084]),
 'Wind Power [MWh/year]-Turbine 1-100': array([ 6.155,  6.177,  6.145, ..., 14.867, 14.969, 15.057]),
 'Wind Power [MWh/year]-Turbine 2-100': array([ 6.13 ,  6.152,  6.12 , ..., 15.019, 15.127, 15.22 ]),
 'Wind Power [MWh/year]-Turbine 3-100': array([ 7.009,  7.034,  6.997, ..., 16.621, 16.718, 16.801]),
 'Wind Power [MWh/year]-Turbine 4-100': array([ 3.403,  3.421,  3.405, ..., 12.082, 12.234, 12.361]),
 'Wind Power [MWh/year]-Turbine 1-150': array([ 7.682,  7.632,  7.582, ..., 15.291, 15.366, 15.432]),
 'Wind Power [MWh/year]-Turbine 2-150': array([ 7.659,  7.608,  7.558, ..., 15.467, 15.546, 15.616]),
 'Wind Power [MWh/year]-Turbine 3-150': array([ 8.737,  8.68 ,  8.623, ..., 17.009, 17.074, 17.132]),
 'Wind Power [MWh/year]-Turbine 4-150': array([ 4.531,  4.5  ,  4.469, ..., 12.718, 12.831, 12.929])}

In [12]:
CFdictionary.update(zip(NormList, NormData))

In [13]:
CFdictionary

{'lat': array([-20.58840942, -20.60075378, -20.61306763, ..., -34.88233185,
        -34.89027405, -34.8982048 ]),
 'lon': array([31.659058, 31.612762, 31.566467, ..., 20.04486 , 19.990234,
        19.935608], dtype=float32),
 'ID': array([    0,     1,     2, ..., 77165, 77166, 77167], dtype=int64),
 'Capacity Factor [%]-Turbine 1-50': array([15.831, 15.938, 15.754, ..., 59.981, 60.608, 61.061]),
 'Capacity Factor [%]-Turbine 2-50': array([15.32 , 15.423, 15.245, ..., 58.741, 59.379, 59.84 ]),
 'Capacity Factor [%]-Turbine 3-50': array([16.23 , 16.34 , 16.152, ..., 60.653, 61.235, 61.651]),
 'Capacity Factor [%]-Turbine 4-50': array([ 7.223,  7.284,  7.195, ..., 42.346, 43.115, 43.678]),
 'Capacity Factor [%]-Turbine 1-80': array([22.427, 22.653, 22.438, ..., 61.962, 62.46 , 62.869]),
 'Capacity Factor [%]-Turbine 2-80': array([21.691, 21.91 , 21.702, ..., 60.758, 61.268, 61.686]),
 'Capacity Factor [%]-Turbine 3-80': array([22.994, 23.225, 23.004, ..., 62.464, 62.902, 63.261]),
 'Capacity Factor [%]-Turbine 4-80': array([10.794, 10.936, 10.831, ..., 44.81 , 45.459, 45.983]),
 'Capacity Factor [%]-Turbine 1-100': array([26.022, 26.115, 25.981, ..., 62.856, 63.288, 63.66 ]),
 'Capacity Factor [%]-Turbine 2-100': array([25.17 , 25.261, 25.131, ..., 61.673, 62.116, 62.496]),
 'Capacity Factor [%]-Turbine 3-100': array([26.67 , 26.764, 26.626, ..., 63.247, 63.614, 63.931]),
 'Capacity Factor [%]-Turbine 4-100': array([12.948, 13.019, 12.958, ..., 45.976, 46.552, 47.034]),
 'Capacity Factor [%]-Turbine 1-150': array([32.481, 32.266, 32.055, ..., 64.65 , 64.965, 65.246]),
 'Capacity Factor [%]-Turbine 2-150': array([31.449, 31.241, 31.037, ..., 63.514, 63.837, 64.125]),
 'Capacity Factor [%]-Turbine 3-150': array([33.247, 33.027, 32.811, ..., 64.723, 64.969, 65.189]),
 'Capacity Factor [%]-Turbine 4-150': array([17.242, 17.122, 17.006, ..., 48.395, 48.824, 49.198]),
 'Wind Power [MWh/year]-Turbine 1-50': array([ 3.744,  3.77 ,  3.726, ..., 14.187, 14.335, 14.442]),
 'Wind Power [MWh/year]-Turbine 2-50': array([ 3.731,  3.756,  3.713, ..., 14.305, 14.46 , 14.573]),
 'Wind Power [MWh/year]-Turbine 3-50': array([ 4.265,  4.294,  4.245, ..., 15.94 , 16.092, 16.202]),
 'Wind Power [MWh/year]-Turbine 4-50': array([ 1.898,  1.914,  1.891, ..., 11.128, 11.331, 11.479]),
 'Wind Power [MWh/year]-Turbine 1-80': array([ 5.304,  5.358,  5.307, ..., 14.655, 14.773, 14.87 ]),
 'Wind Power [MWh/year]-Turbine 2-80': array([ 5.282,  5.336,  5.285, ..., 14.796, 14.92 , 15.022]),
 'Wind Power [MWh/year]-Turbine 3-80': array([ 6.043,  6.104,  6.045, ..., 16.416, 16.531, 16.625]),
 'Wind Power [MWh/year]-Turbine 4-80': array([ 2.837,  2.874,  2.846, ..., 11.776, 11.947, 12.084]),
 'Wind Power [MWh/year]-Turbine 1-100': array([ 6.155,  6.177,  6.145, ..., 14.867, 14.969, 15.057]),
 'Wind Power [MWh/year]-Turbine 2-100': array([ 6.13 ,  6.152,  6.12 , ..., 15.019, 15.127, 15.22 ]),
 'Wind Power [MWh/year]-Turbine 3-100': array([ 7.009,  7.034,  6.997, ..., 16.621, 16.718, 16.801]),
 'Wind Power [MWh/year]-Turbine 4-100': array([ 3.403,  3.421,  3.405, ..., 12.082, 12.234, 12.361]),
 'Wind Power [MWh/year]-Turbine 1-150': array([ 7.682,  7.632,  7.582, ..., 15.291, 15.366, 15.432]),
 'Wind Power [MWh/year]-Turbine 2-150': array([ 7.659,  7.608,  7.558, ..., 15.467, 15.546, 15.616]),
 'Wind Power [MWh/year]-Turbine 3-150': array([ 8.737,  8.68 ,  8.623, ..., 17.009, 17.074, 17.132]),
 'Wind Power [MWh/year]-Turbine 4-150': array([ 4.531,  4.5  ,  4.469, ..., 12.718, 12.831, 12.929]),
 'loc-50': array([4.451085 , 4.450384 , 4.426683 , ..., 8.4077835, 8.495468 ,
        8.560455 ], dtype=float32),
 'scale-50': array([1.9601946, 1.9799922, 1.9828206, ..., 4.172633 , 4.2274327,
        4.268422 ], dtype=float32),
 'loc-80': array([4.965874 , 4.9759183, 4.9473934, ..., 8.693491 , 8.77089  ,
        8.834531 ], dtype=float32),
 'scale-80': array([2.2905073, 2.3137336, 2.3248093, ..., 4.352286 , 4.4047813,
        4.4440274], dtype=float32),
 'loc-100': array([5.2286363, 5.230099 , 5.2111034, ..., 8.833422 , 8.903991 ,
        8.964262 ], dtype=float32),
 'scale-100': array([2.4731205, 2.4883132, 2.499546 , ..., 4.4460163, 4.4947677,
        4.5319333], dtype=float32),
 'loc-150': array([5.710529, 5.687214, 5.663712, ..., 9.137693, 9.194032, 9.243718],
       dtype=float32),
 'scale-150': array([2.7926266, 2.7998679, 2.8081205, ..., 4.6552663, 4.6928797,
        4.723182 ], dtype=float32)}

In [14]:
CFdictionary
CFdf = pd.DataFrame(CFdictionary)
SaveTo=open(r"C:\Users\futil\OneDrive\GIZ/Internship/seb_test_ring/rose/maker/Test_CF004.csv",mode='w')

CFdf.to_csv(SaveTo,index=False)
SaveTo.close()

In [15]:
CFdf

,lat,lon,ID,Capacity Factor [%]-Turbine 1-50,Capacity Factor [%]-Turbine 2-50,Capacity Factor [%]-Turbine 3-50,Capacity Factor [%]-Turbine 4-50,Capacity Factor [%]-Turbine 1-80,Capacity Factor [%]-Turbine 2-80,Capacity Factor [%]-Turbine 3-80,...,Wind Power [MWh/year]-Turbine 3-150,Wind Power [MWh/year]-Turbine 4-150,loc-50,scale-50,loc-80,scale-80,loc-100,scale-100,loc-150,scale-150
0,-20.588409,31.659058,0,15.831,15.320,16.230,7.223,22.427,21.691,22.994,...,8.737,4.531,4.451085,1.960195,4.965874,2.290507,5.228636,2.473120,5.710529,2.792627
1,-20.600754,31.612762,1,15.938,15.423,16.340,7.284,22.653,21.910,23.225,...,8.680,4.500,4.450384,1.979992,4.975918,2.313734,5.230099,2.488313,5.687214,2.799868
2,-20.613068,31.566467,2,15.754,15.245,16.152,7.195,22.438,21.702,23.004,...,8.623,4.469,4.426683,1.982821,4.947393,2.324809,5.211103,2.499546,5.663712,2.808120
3,-20.625374,31.520172,3,15.594,15.090,15.988,7.117,22.177,21.450,22.737,...,8.579,4.447,4.407991,1.982221,4.918148,2.328583,5.185576,2.509165,5.644298,2.817373
4,-20.631729,31.672241,4,15.167,14.677,15.549,6.903,21.673,20.963,22.221,...,8.530,4.412,4.365050,1.969711,4.881004,2.302014,5.156966,2.493521,5.631883,2.804544
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77163,-34.869171,19.816711,77163,61.176,59.962,61.741,43.884,63.093,61.916,63.450,...,17.207,13.048,8.582253,4.299032,8.871519,4.471255,9.011371,4.557921,9.304466,4.753407
77164,-34.874355,20.099487,77164,59.295,58.044,60.008,41.520,61.412,60.196,61.974,...,16.933,12.586,8.314796,4.116031,8.609934,4.294335,8.755575,4.390313,9.072704,4.609669
77165,-34.882332,20.044861,77165,59.981,58.741,60.653,42.346,61.962,60.758,62.464,...,17.009,12.718,8.407784,4.172633,8.693491,4.352286,8.833422,4.446016,9.137693,4.655266
77166,-34.890274,19.990234,77166,60.608,59.379,61.235,43.115,62.460,61.268,62.902,...,17.074,12.831,8.495468,4.227433,8.770890,4.404781,8.903991,4.494768,9.194032,4.692880
77167,-34.898205,19.935608,77167,61.061,59.840,61.651,43.678,62.869,61.686,63.261,...,17.132,12.929,8.560455,4.268422,8.834531,4.444027,8.964262,4.531933,9.243718,4.723182

In [16]:
Names=["N","NNE","NE","ENE","E","ESE","SE","SSE","S","SSW","SW","WSW","W","WNW","NW","NNW"]
HGT=["50","80","100","150"]
RoseList=[]
for i in HGT:
    NameDir=list(map(lambda x: x+"-"+i,Names))
    RoseList.extend(NameDir)

# Rosedictionary = {'lat': np.array(da['lat']), 'lon': np.array(da['lon']),'ID':np.array(da['ID'])}
Rosedictionary = {'ID':np.array(da['ID'])}

RoseData=[]

for i in np.array(da['hgt']):
    for j in np.array(da['RoseDir']):
        RoseData.append(np.array(da['Rose'].sel(hgt=i,RoseDir=j)))

print(np.array(da['RoseDir']))
print(np.shape(RoseData))

Rosedictionary.update(zip(RoseList, RoseData))

['N' 'NNE' 'NE' 'ENE' 'E' 'ESE' 'SE' 'SSE' 'S' 'SSW' 'SW' 'WSW' 'W' 'WNW'
 'NW' 'NNW']
(64, 77168)

In [17]:
Rosedictionary

{'ID': array([    0,     1,     2, ..., 77165, 77166, 77167], dtype=int64),
 'N-50': array([6.966, 7.175, 7.311, ..., 1.775, 1.529, 1.377]),
 'NNE-50': array([5.654, 5.615, 5.51 , ..., 1.551, 1.515, 1.433]),
 'NE-50': array([5.175, 5.223, 5.194, ..., 2.012, 2.103, 2.069]),
 'ENE-50': array([7.038, 6.997, 6.967, ..., 6.909, 6.952, 6.685]),
 'E-50': array([10.278, 10.107, 10.033, ..., 15.127, 15.264, 15.468]),
 'ESE-50': array([13.958, 14.106, 14.432, ..., 10.06 , 10.184, 10.547]),
 'SE-50': array([14.669, 15.152, 15.671, ...,  6.117,  6.105,  6.098]),
 'SSE-50': array([11.007, 10.814, 10.49 , ...,  4.224,  4.204,  4.255]),
 'S-50': array([6.041, 5.637, 5.186, ..., 3.763, 3.722, 3.75 ]),
 'SSW-50': array([3.347, 3.131, 2.966, ..., 3.768, 3.737, 3.704]),
 'SW-50': array([2.683, 2.557, 2.419, ..., 5.316, 5.156, 5.082]),
 'WSW-50': array([2.24 , 2.19 , 2.157, ..., 8.828, 8.398, 8.207]),
 'W-50': array([ 1.663,  1.765,  1.814, ..., 14.477, 14.208, 13.701]),
 'WNW-50': array([ 1.511,  1.602,  1.731, ..., 10.232, 11.236, 11.972]),
 'NW-50': array([2.446, 2.516, 2.665, ..., 4.024, 4.056, 4.139]),
 'NNW-50': array([5.322, 5.413, 5.454, ..., 1.816, 1.632, 1.514]),
 'N-80': array([6.294, 6.401, 6.294, ..., 1.397, 1.179, 1.126]),
 'NNE-80': array([5.711, 5.56 , 5.405, ..., 1.509, 1.394, 1.268]),
 'NE-80': array([5.459, 5.3  , 5.264, ..., 2.18 , 2.211, 2.128]),
 'ENE-80': array([7.103, 7.127, 7.174, ..., 7.002, 7.075, 6.817]),
 'E-80': array([11.06 , 10.915, 10.963, ..., 15.219, 15.334, 15.466]),
 'ESE-80': array([14.987, 15.243, 15.567, ..., 10.01 , 10.169, 10.485]),
 'SE-80': array([15.528, 16.059, 16.531, ...,  6.098,  6.071,  6.119]),
 'SSE-80': array([11.275, 11.15 , 10.782, ...,  4.192,  4.179,  4.221]),
 'S-80': array([6.05 , 5.645, 5.225, ..., 3.782, 3.754, 3.802]),
 'SSW-80': array([3.394, 3.224, 3.015, ..., 3.787, 3.761, 3.701]),
 'SW-80': array([2.719, 2.622, 2.548, ..., 5.302, 5.116, 5.082]),
 'WSW-80': array([2.143, 2.145, 2.15 , ..., 8.936, 8.483, 8.257]),
 'W-80': array([ 1.516,  1.589,  1.689, ..., 14.706, 14.411, 13.862]),
 'WNW-80': array([ 1.431,  1.467,  1.602, ..., 10.52 , 11.463, 12.188]),
 'NW-80': array([1.799, 1.933, 2.09 , ..., 3.826, 3.928, 4.054]),
 'NNW-80': array([3.532, 3.618, 3.702, ..., 1.532, 1.472, 1.425]),
 'N-100': array([5.94 , 5.942, 5.858, ..., 1.188, 1.031, 0.979]),
 'NNE-100': array([5.608, 5.482, 5.203, ..., 1.443, 1.306, 1.202]),
 'NE-100': array([5.621, 5.489, 5.321, ..., 2.191, 2.154, 2.033]),
 'ENE-100': array([7.224, 7.15 , 7.127, ..., 7.082, 7.199, 6.973]),
 'E-100': array([11.333, 11.225, 11.343, ..., 15.279, 15.351, 15.436]),
 'ESE-100': array([15.554, 15.889, 16.263, ..., 10.018, 10.161, 10.473]),
 'SE-100': array([15.998, 16.525, 17.092, ...,  6.048,  6.045,  6.098]),
 'SSE-100': array([11.4  , 11.254, 10.954, ...,  4.179,  4.156,  4.2  ]),
 'S-100': array([6.001, 5.611, 5.23 , ..., 3.779, 3.775, 3.815]),
 'SSW-100': array([3.347, 3.199, 3.071, ..., 3.832, 3.795, 3.719]),
 'SW-100': array([2.651, 2.561, 2.507, ..., 5.307, 5.136, 5.147]),
 'WSW-100': array([2.046, 2.023, 2.031, ..., 9.004, 8.513, 8.276]),
 'W-100': array([ 1.431,  1.51 ,  1.628, ..., 14.868, 14.559, 13.959]),
 'WNW-100': array([ 1.391,  1.431,  1.504, ..., 10.686, 11.648, 12.356]),
 'NW-100': array([1.523, 1.701, 1.794, ..., 3.642, 3.783, 3.946]),
 'NNW-100': array([2.93 , 3.011, 3.075, ..., 1.452, 1.389, 1.387]),
 'N-150': array([5.716, 5.569, 5.424, ..., 0.994, 0.884, 0.865]),
 'NNE-150': array([5.464, 5.248, 5.006, ..., 1.288, 1.123, 1.055]),
 'NE-150': array([5.326, 5.3  , 5.2  , ..., 2.165, 2.064, 1.911]),
 'ENE-150': array([7.681, 7.686, 7.585, ..., 7.183, 7.318, 7.127]),
 'E-150': array([11.921, 11.875, 12.015, ..., 15.366, 15.404, 15.49 ]),
 'ESE-150': array([16.345, 16.794, 17.298, ...,  9.92 , 10.098, 10.329]),
 'SE-150': array([16.856, 17.277, 17.704, ...,  5.988,  5.978,  6.038]),
 'SSE-150': array([11.368, 11.142, 10.815, ...,  4.1  ,  4.103,  4.147]),
 'S-150': array([5.749, 5.358, 4.98 , ..., 3.802, 3.787, 3.832]),
 'SSW-150': array([3.18 , 3.029, 2.885, ..., 3.929, 3.843, 3.756]),
 'SW-150': array([2.482, 2.428, 2.401, ..., 5.311, 5.192, 5.181]),
 'WSW-150': array([1.82 , 1.819, 1.826, ..., 9.073, 8.624, 8.4  ]),
 'W-150': array([ 1.304,  1.408,  1.513, ..., 15.255, 14.755, 14.139]),
 'WNW-150': array([ 1.297,  1.394,  1.482, ..., 11.07 , 12.135, 12.828]),
 'NW-150': array([1.238, 1.371, 1.521, ..., 3.244, 3.424, 3.653]),
 'NNW-150': array([2.252, 2.302, 2.344, ..., 1.311, 1.265, 1.249])}

In [18]:
Rosedf = pd.DataFrame(Rosedictionary)
# da['Rose'].sel(hgt=50,RoseDir="N")

SaveTo=open(r"C:\Users\futil\OneDrive\GIZ/Internship/seb_test_ring/rose/maker/Test_Rose004.csv",mode='w')

Rosedf.to_csv(SaveTo,index=False)
SaveTo.close()

Rosedf

,ID,N-50,NNE-50,NE-50,ENE-50,E-50,ESE-50,SE-50,SSE-50,S-50,...,SE-150,SSE-150,S-150,SSW-150,SW-150,WSW-150,W-150,WNW-150,NW-150,NNW-150
0,0,6.966,5.654,5.175,7.038,10.278,13.958,14.669,11.007,6.041,...,16.856,11.368,5.749,3.180,2.482,1.820,1.304,1.297,1.238,2.252
1,1,7.175,5.615,5.223,6.997,10.107,14.106,15.152,10.814,5.637,...,17.277,11.142,5.358,3.029,2.428,1.819,1.408,1.394,1.371,2.302
2,2,7.311,5.510,5.194,6.967,10.033,14.432,15.671,10.490,5.186,...,17.704,10.815,4.980,2.885,2.401,1.826,1.513,1.482,1.521,2.344
3,3,7.333,5.348,5.159,6.836,10.017,14.994,16.199,10.146,4.767,...,18.206,10.420,4.654,2.741,2.368,1.820,1.555,1.589,1.627,2.434
4,4,6.812,5.701,5.330,7.236,10.405,13.946,14.457,10.670,5.858,...,16.719,11.144,5.689,3.250,2.663,1.940,1.370,1.304,1.265,2.128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77163,77163,1.205,1.359,2.272,6.249,15.585,11.089,6.141,4.139,3.706,...,6.054,4.070,3.751,3.644,4.957,7.931,13.473,13.832,4.162,1.119
77164,77164,1.930,1.427,1.810,6.604,15.279,10.086,6.200,4.229,3.815,...,6.023,4.158,3.811,3.962,5.478,9.499,15.217,10.291,3.320,1.378
77165,77165,1.775,1.551,2.012,6.909,15.127,10.060,6.117,4.224,3.763,...,5.988,4.100,3.802,3.929,5.311,9.073,15.255,11.070,3.244,1.311
77166,77166,1.529,1.515,2.103,6.952,15.264,10.184,6.105,4.204,3.722,...,5.978,4.103,3.787,3.843,5.192,8.624,14.755,12.135,3.424,1.265
77167,77167,1.377,1.433,2.069,6.685,15.468,10.547,6.098,4.255,3.750,...,6.038,4.147,3.832,3.756,5.181,8.400,14.139,12.828,3.653,1.249

In [19]:
WindDF=pd.read_csv('https://raw.githubusercontent.com/Futile21/CSV_wind/master/Test_CF004.csv')

In [20]:
WindDF

,lat,lon,ID,CF-Turbine 1-50,CF-Turbine 2-50,CF-Turbine 3-50,CF-Turbine 4-50,CF-Turbine 1-80,CF-Turbine 2-80,CF-Turbine 3-80,...,WindPower-Turbine 3-150,WindPower-Turbine 4-150,loc-50,scale-50,loc-80,scale-80,loc-100,scale-100,loc-150,scale-150
0,-20.588409,31.659058,0,15.831,15.320,16.230,7.223,22.427,21.691,22.994,...,8.737,4.531,4.451085,1.960195,4.965874,2.290507,5.228636,2.473121,5.710529,2.792627
1,-20.600754,31.612762,1,15.938,15.423,16.340,7.284,22.653,21.910,23.225,...,8.680,4.500,4.450384,1.979992,4.975918,2.313734,5.230099,2.488313,5.687214,2.799868
2,-20.613068,31.566467,2,15.754,15.245,16.152,7.195,22.438,21.702,23.004,...,8.623,4.469,4.426683,1.982821,4.947393,2.324809,5.211103,2.499546,5.663712,2.808121
3,-20.625374,31.520172,3,15.594,15.090,15.988,7.117,22.177,21.450,22.737,...,8.579,4.447,4.407991,1.982221,4.918148,2.328583,5.185576,2.509165,5.644298,2.817373
4,-20.631729,31.672241,4,15.167,14.677,15.549,6.903,21.673,20.963,22.221,...,8.530,4.412,4.365050,1.969711,4.881004,2.302014,5.156966,2.493521,5.631883,2.804544
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77163,-34.869171,19.816711,77163,61.176,59.962,61.741,43.884,63.093,61.916,63.450,...,17.207,13.048,8.582253,4.299032,8.871519,4.471255,9.011371,4.557921,9.304466,4.753407
77164,-34.874355,20.099487,77164,59.295,58.044,60.008,41.520,61.412,60.196,61.974,...,16.933,12.586,8.314796,4.116031,8.609934,4.294335,8.755575,4.390313,9.072704,4.609669
77165,-34.882332,20.044860,77165,59.981,58.741,60.653,42.346,61.962,60.758,62.464,...,17.009,12.718,8.407784,4.172633,8.693491,4.352286,8.833422,4.446016,9.137693,4.655266
77166,-34.890274,19.990234,77166,60.608,59.379,61.235,43.115,62.460,61.268,62.902,...,17.074,12.831,8.495468,4.227433,8.770890,4.404781,8.903991,4.494768,9.194032,4.692880
77167,-34.898205,19.935608,77167,61.061,59.840,61.651,43.678,62.869,61.686,63.261,...,17.132,12.929,8.560455,4.268422,8.834531,4.444027,8.964262,4.531933,9.243718,4.723182

In [24]:
ID=20
np.array(WindDF[(WindDF['ID'] == ID)]['scale-50'])

array([1.9242188])

In [25]:
WindDF['lat']

0       -20.588409
1       -20.600754
2       -20.613068
3       -20.625374
4       -20.631729
           ...
77163   -34.869171
77164   -34.874355
77165   -34.882332
77166   -34.890274
77167   -34.898205
Name: lat, Length: 77168, dtype: float64

In [26]:
np.array(WindDF[(WindDF['ID'] == ID)]['CF-Turbine 1-50']).flatten()

array([14.011])

In [53]:
np.array(WindDF['CF-Turbine 1-50']).flatten()

array([15.831, 15.938, 15.754, ..., 59.981, 60.608, 61.061])

In [54]:
x='Turbine 1'
y='50'

w=x+'-'+y

In [55]:
w

'Turbine 1-50'

In [60]:
TurbDF=pd.read_csv('https://raw.githubusercontent.com/Futile21/CSV_wind/master/PowerTurb4.csv')
TurbDF

    Speed  Turbine 1  Turbine 2  Turbine 3  Turbine 4
0       1        0.0        0.0        0.0        0.0
1       2        0.0        0.0        0.0        0.0
2       3       29.0       25.0       33.0        0.0
3       4      171.0      171.0      194.0       77.0
4       5      389.0      389.0      442.0      190.0
5       6      703.0      704.0      802.0      353.0
6       7     1139.0     1136.0     1298.0      581.0
7       8     1682.0     1674.0     1915.0      886.0
8       9     2205.0     2173.0     2533.0     1273.0
9      10     2541.0     2518.0     2881.0     1710.0
10     11     2669.0     2696.0     2997.0     2145.0
11     12     2697.0     2766.0     3000.0     2544.0
12     13     2700.0     2780.0     3000.0     2837.0
13     14     2700.0     2780.0     3000.0     2965.0
14     15     2700.0     2780.0     3000.0     2995.0
15     16     2700.0     2780.0     3000.0     3000.0
16     17     2700.0     2780.0     3000.0     3000.0
17     18     2700.0     2780.0     3000.0     3000.0
18     19     2700.0     2780.0     3000.0     3000.0
19     20     2700.0     2780.0     3000.0     3000.0
20     21     2700.0     2780.0        0.0     3000.0
21     22     2700.0     2780.0        0.0     3000.0
22     23     2700.0     2780.0        0.0     3000.0
23     24     2700.0     2780.0        0.0     3000.0
24     25     2700.0     2780.0        0.0     3000.0
25     26        0.0        0.0        0.0        0.0

In [62]:
np.array(TurbDF['Turbine 1'])

array([   0.,    0.,   29.,  171.,  389.,  703., 1139., 1682., 2205.,
       2541., 2669., 2697., 2700., 2700., 2700., 2700., 2700., 2700.,
       2700., 2700., 2700., 2700., 2700., 2700., 2700.,    0.])

In [63]:
RoseDF=pd.read_csv('https://raw.githubusercontent.com/Futile21/CSV_wind/master/Test_Rose003.csv')
RoseDF

,ID,N-50,NNE-50,NE-50,ENE-50,E-50,ESE-50,SE-50,SSE-50,S-50,...,SE-150,SSE-150,S-150,SSW-150,SW-150,WSW-150,W-150,WNW-150,NW-150,NNW-150
0,0,6.966,5.654,5.175,7.038,10.278,13.958,14.669,11.007,6.041,...,16.856,11.368,5.749,3.180,2.482,1.820,1.304,1.297,1.238,2.252
1,1,7.175,5.615,5.223,6.997,10.107,14.106,15.152,10.814,5.637,...,17.277,11.142,5.358,3.029,2.428,1.819,1.408,1.394,1.371,2.302
2,2,7.311,5.510,5.194,6.967,10.033,14.432,15.671,10.490,5.186,...,17.704,10.815,4.980,2.885,2.401,1.826,1.513,1.482,1.521,2.344
3,3,7.333,5.348,5.159,6.836,10.017,14.994,16.199,10.146,4.767,...,18.206,10.420,4.654,2.741,2.368,1.820,1.555,1.589,1.627,2.434
4,4,6.812,5.701,5.330,7.236,10.405,13.946,14.457,10.670,5.858,...,16.719,11.144,5.689,3.250,2.663,1.940,1.370,1.304,1.265,2.128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77163,77163,1.205,1.359,2.272,6.249,15.585,11.089,6.141,4.139,3.706,...,6.054,4.070,3.751,3.644,4.957,7.931,13.473,13.832,4.162,1.119
77164,77164,1.930,1.427,1.810,6.604,15.279,10.086,6.200,4.229,3.815,...,6.023,4.158,3.811,3.962,5.478,9.499,15.217,10.291,3.320,1.378
77165,77165,1.775,1.551,2.012,6.909,15.127,10.060,6.117,4.224,3.763,...,5.988,4.100,3.802,3.929,5.311,9.073,15.255,11.070,3.244,1.311
77166,77166,1.529,1.515,2.103,6.952,15.264,10.184,6.105,4.204,3.722,...,5.978,4.103,3.787,3.843,5.192,8.624,14.755,12.135,3.424,1.265
77167,77167,1.377,1.433,2.069,6.685,15.468,10.547,6.098,4.255,3.750,...,6.038,4.147,3.832,3.756,5.181,8.400,14.139,12.828,3.653,1.249

In [ ]:
NamesDir=["N","NNE","NE","ENE","E","ESE","SE","SSE","S","SSW","SW","WSW","W","WNW","NW","NNW"]
HGT=["50","80","100","150"]
RoseList=[]
for i in HGT:
    NameDir=list(map(lambda x: x+"-"+i,Names))
    RoseList.extend(NameDir)

In [64]:
Height='50'

In [66]:
Dir=list(map(lambda x: x+"-"+Height,NamesDir))
Dir

['N-50',
 'NNE-50',
 'NE-50',
 'ENE-50',
 'E-50',
 'ESE-50',
 'SE-50',
 'SSE-50',
 'S-50',
 'SSW-50',
 'SW-50',
 'WSW-50',
 'W-50',
 'WNW-50',
 'NW-50',
 'NNW-50']

In [71]:
n=list(RoseDF[(RoseDF['ID'] == ID)][Dir])
n

['N-50',
 'NNE-50',
 'NE-50',
 'ENE-50',
 'E-50',
 'ESE-50',
 'SE-50',
 'SSE-50',
 'S-50',
 'SSW-50',
 'SW-50',
 'WSW-50',
 'W-50',
 'WNW-50',
 'NW-50',
 'NNW-50']

In [76]:
v=n[0]
n.append(n[0])

In [77]:
n

['N-50',
 'NNE-50',
 'NE-50',
 'ENE-50',
 'E-50',
 'ESE-50',
 'SE-50',
 'SSE-50',
 'S-50',
 'SSW-50',
 'SW-50',
 'WSW-50',
 'W-50',
 'WNW-50',
 'NW-50',
 'NNW-50',
 'N',
 '-',
 '5',
 '0',
 'N',
 '-',
 '5',
 '0',
 'N-50']

In [ ]:
git remote add origin https://github.com/Futile21/CSV_wind.git